version: '3.8'

services:
  backend-container:
    build: ./back-end
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    env_file: .env
    depends_on: database
  
  frontend:
    build: ./requirements/frontend
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - vue-dev:/app
    env_file: .env
    depends_on: database

  db-container:
    build: ./database
    ports:
      - 5432-5433:5432-5433
    env_file: ./.env
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - transcendence_net

volumes:
  db-data:
  vue-dev:

networks:
  transcendence_net:
