version: '3'

services:
  backend:
    build: ./requirements/backend
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: .env
    depends_on: database
  
  frontend:
    build: ./requirements/frontend
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - vue-dev:/app
    env_file: .env
    depends_on: database

  database:
    image: postgres
    environment:
      - POSTGRES_USER=ping
      - POSTGRES_PASSWORD=pong
      - POSTGRES_DB=pong_db
    ports:
      - 5432:5432
    env_file: ./.env
    volumes: 
      - database:/var/lib/postgresql/data

volumes:
  database:
  vue-dev:

# questions: only one or two container? why vue_dev