version: '3.9'

services:
  db-container:
    container_name: db-container
    image: postgres:16
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - transcendence-net

  backend-container:
    container_name: backend-container
    build: ./backend
    depends_on:
      - db-container
    env_file:
      - .env
    ports:
      - "3000:3000" # general/api
      - "5174:5174" # game server
      - "9000:9000" # chat server
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - transcendence-net
    
  frontend-container:
    container_name: frontend-container
    build: ./frontend
    environment:
      - VITE_CURRENT_HOST=${CURRENT_HOST}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - transcendence-net

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - db-container
    ports:
      - "8080:8080"
    networks:
      - transcendence-net

volumes:
  db-data:

networks:
  transcendence-net:
