version: '3.9'

services:
  db-container:
    image: postgres:16
    container_name: db
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  backend-container:
    build: ./back-end
    ports:
      - "3000:3000"
    depends_on:
      - db-container
    env_file:
      - .env
    volumes:
      - ./back-end:/app
      - /app/node_modules

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db-container

volumes:
  db-data:
