version: '3.8'

services:

  app-container:
    build:
      context: ./app-container
      dockerfile: backend.Dockerfile
    ports:
      - 80:80
      - 443:443
    env_file: ./env
    volumes:
      - vue-dev:/app
    depends_on: db-container


  db-container:
    build: ./db-container
    ports:
      - 5432:5432
    env_file: ./env
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
  vue-dev: 